/* ProyecIoT85
  Sketch generated by the Arduino IoT Cloud Thing "Prueba"
  https://create.arduino.cc/cloud/things/0cfefd6c-7408-46e4-be37-25b630067b4b

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temperatura;
  bool relay1;
  bool relay2;
  bool relay3;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include "thingProperties.h"


String estado1;
String estado2;
String estado3;
Adafruit_SSD1306 display(-1);


///Temperatura///
//float temp=0;
float pinLM35 = 0;
int AC1 = 14;
int AC2 = 12;
int AC3 = 13;

void setup() {
  pinMode(pinLM35, INPUT);
  pinMode(AC1, OUTPUT);
  pinMode(AC2, OUTPUT);
  pinMode(AC3, OUTPUT);
  // initialize with the I2C addr 0x3C
  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);

  // Clear the buffer.
  display.clearDisplay();
  Serial.begin(9600);
  delay(1500);

  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

}

void loop() {
  ArduinoCloud.update();
  //temperatura=;
  temperatura = (3.3 * analogRead(pinLM35) * 100.0) / 1024.0;
  //onTempChange() ;
  display.setTextSize(1);
  display.setTextColor(WHITE);
  display.setCursor(0, 0);
  display.println("AC1: ");
  display.setCursor(23, 0);
  display.println(estado1);
  display.setCursor(42, 0);
  display.println("AC2: ");
  display.setCursor(65, 0);
  display.println(estado2);
  display.setCursor(85, 0);
  display.println("AC3: ");
  display.setCursor(109, 0);
  display.println(estado3);
  //temperatura//
  display.setCursor(0, 12);
  display.println("TEM: ");
  display.setCursor(23, 12);
  display.println(temperatura);
  display.setCursor(60, 12);
  display.println("C");
  ///////////
  display.display();
  display.clearDisplay();

}
void onRelay1Change()  {
  if (relay1)
  {
    digitalWrite(AC1, HIGH);
    estado1 = "ON";

  }
  else
  {
    digitalWrite(AC1, LOW);
    estado1 = "OFF";

  }
}
void onRelay2Change()  {
  if (relay2)
  {
    digitalWrite(AC2, HIGH);
    estado2 = "ON";
  }
  else
  {
    digitalWrite(AC2, LOW);
    estado2 = "OFF";
  }

}

void onRelay3Change()  {
  if (relay3)
  {
    digitalWrite(AC3, HIGH);
    estado3 = "ON";
  }
  else
  {
    digitalWrite(AC3, LOW);
    estado3 = "OFF";

  }
}
void onTempChange()  {

}
